export const DB_SCHEMA_VERSION = 7

export const LEGACY_WORKSPACE_STATE_KEY = 'workspace-state-raw'

export const DEFAULT_MAX_WORKSPACE_STATE_RAW_BYTES = 50 * 1024 * 1024

export const MAX_PERSISTED_SCROLLBACK_CHARS = 400_000
