import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, storageKey } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Node Create (Push-away)', () => {
  test('keeps blocking windows fixed and creates the task in a nearby vacancy', async () => {
    const { electronApp, window } = await launchApp()
    const clickPosition = { x: 280, y: 220 }

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'crowded-existing-task',
          title: 'existing-task',
          position: { x: 320, y: 220 },
          width: 460,
          height: 280,
          kind: 'task',
          status: null,
          task: {
            requirement: 'existing',
            status: 'todo',
            priority: 'medium',
            tags: [],
            linkedAgentNodeId: null,
            agentSessions: [],
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: '2026-02-15T00:00:00.000Z',
            updatedAt: '2026-02-15T00:00:00.000Z',
          },
        },
      ])

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()

      await pane.click({
        button: 'right',
        position: clickPosition,
      })
      await window.locator('[data-testid="workspace-context-new-task"]').click()

      await expect(window.locator('[data-testid="workspace-task-creator"]')).toBeVisible()
      await window.locator('[data-testid="workspace-task-advanced-toggle"]').click()
      await window.locator('[data-testid="workspace-task-title"]').fill('Crowded Task')
      await window.locator('[data-testid="workspace-task-requirement"]').fill('push-away-on-create')
      await window.locator('[data-testid="workspace-task-create-submit"]').click()

      await expect(window.locator('.task-node')).toHaveCount(2)

      const snapshot = await window.evaluate(async key => {
        void key

        const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id?: string
              kind?: string
              position?: { x?: number; y?: number }
              width?: number
              height?: number
              task?: { requirement?: string } | null
            }>
          }>
        }

        const workspace = parsed.workspaces?.[0]
        const nodes = workspace?.nodes ?? []
        const created = nodes.find(
          node => node.kind === 'task' && node.task?.requirement === 'push-away-on-create',
        )
        const existing = nodes.find(node => node.id === 'crowded-existing-task')

        if (
          !created?.position ||
          typeof created.position.x !== 'number' ||
          typeof created.width !== 'number' ||
          !existing?.position ||
          typeof existing.position.x !== 'number'
        ) {
          return null
        }

        return {
          createdX: created.position.x,
          createdY: created.position.y,
          createdWidth: created.width,
          createdHeight: created.height,
          existingX: existing.position.x,
          existingY: existing.position.y ?? null,
        }
      }, storageKey)

      if (!snapshot) {
        throw new Error('failed to read persisted crowded create snapshot')
      }

      expect(snapshot.existingX).toBe(320)
      expect(snapshot.existingY).toBe(220)

      const createdRight = snapshot.createdX + snapshot.createdWidth
      const createdBottom = snapshot.createdY + snapshot.createdHeight
      const existingRight = snapshot.existingX + 460
      const existingBottom = snapshot.existingY + 280

      expect(
        createdRight <= snapshot.existingX ||
          snapshot.createdX >= existingRight ||
          createdBottom <= snapshot.existingY ||
          snapshot.createdY >= existingBottom,
      ).toBe(true)

      const createdTaskNode = window
        .locator('.task-node')
        .filter({ hasText: 'Crowded Task' })
        .first()
      await expect(createdTaskNode).toBeVisible()
      await expect(pane).toBeVisible()

      const bounds = await createdTaskNode.boundingBox()
      const paneBounds = await pane.boundingBox()

      if (!bounds || !paneBounds) {
        throw new Error('failed to resolve created task or pane bounds')
      }

      const centeredX = bounds.x + bounds.width / 2
      const centeredY = bounds.y + bounds.height / 2

      expect(Math.abs(centeredX - (paneBounds.x + paneBounds.width / 2))).toBeLessThanOrEqual(48)
      expect(Math.abs(centeredY - (paneBounds.y + paneBounds.height / 2))).toBeLessThanOrEqual(48)
    } finally {
      await electronApp.close()
    }
  })
})
