import { expect, test } from '@playwright/test'
import { launchApp, seedWorkspaceState, testWorkspacePath } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Tasks (Agent Session Menu)', () => {
  test('anchors the task agent session menu to the right-click point', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await seedWorkspaceState(window, {
        activeWorkspaceId: 'workspace-task-session-menu',
        workspaces: [
          {
            id: 'workspace-task-session-menu',
            name: 'workspace-task-session-menu',
            path: testWorkspacePath,
            nodes: [
              {
                id: 'task-session-menu-node',
                title: 'Task Session Menu',
                position: { x: 220, y: 180 },
                width: 420,
                height: 280,
                kind: 'task',
                task: {
                  requirement: 'Verify the session menu anchor',
                  status: 'doing',
                  priority: 'medium',
                  tags: [],
                  linkedAgentNodeId: null,
                  agentSessions: [
                    {
                      id: 'session-1',
                      provider: 'codex',
                      resumeSessionId: 'resume-1',
                      resumeSessionIdVerified: true,
                      prompt: 'Inspect menu placement',
                      model: 'gpt-5.2-codex',
                      effectiveModel: 'gpt-5.2-codex',
                      boundDirectory: testWorkspacePath,
                      lastDirectory: testWorkspacePath,
                      createdAt: '2026-02-08T15:00:00.000Z',
                      lastRunAt: '2026-02-08T15:00:00.000Z',
                      endedAt: '2026-02-08T15:10:00.000Z',
                      exitCode: 0,
                      status: 'exited',
                    },
                  ],
                  lastRunAt: '2026-02-08T15:00:00.000Z',
                  autoGeneratedTitle: false,
                  createdAt: null,
                  updatedAt: null,
                },
              },
            ],
          },
        ],
      })

      const sessionRecord = window.locator(
        '[data-testid="task-node-agent-session-record-session-1"]',
      )
      await expect(sessionRecord).toBeVisible()

      const recordBox = await sessionRecord.boundingBox()
      expect(recordBox).not.toBeNull()
      if (!recordBox) {
        return
      }

      const clickPosition = { x: 28, y: 22 }
      await sessionRecord.click({
        button: 'right',
        position: clickPosition,
      })

      const menu = window.locator('[data-testid="task-node-agent-session-menu"]')
      await expect(menu).toBeVisible()

      const menuBox = await menu.boundingBox()
      expect(menuBox).not.toBeNull()
      if (!menuBox) {
        return
      }

      expect(Math.abs(menuBox.x - (recordBox.x + clickPosition.x))).toBeLessThanOrEqual(16)
      expect(Math.abs(menuBox.y - (recordBox.y + clickPosition.y))).toBeLessThanOrEqual(16)
    } finally {
      await electronApp.close()
    }
  })
})
