import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'

async function seedCodexTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-agent-last-message',
        title: 'Capture agent answer',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Wait for standby and save the last agent message as a note',
          status: 'todo',
          priority: 'medium',
          tags: ['notes'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-03-15T00:00:00.000Z',
          updatedAt: '2026-03-15T00:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'codex',
        customModelEnabledByProvider: {
          'claude-code': false,
          codex: true,
        },
        customModelByProvider: {
          'claude-code': '',
          codex: 'gpt-5.2-codex',
        },
        customModelOptionsByProvider: {
          'claude-code': [],
          codex: ['gpt-5.2-codex'],
        },
      },
    },
  )
}

test.describe('Workspace Canvas - Agent Last Message To Note', () => {
  test('creates a note from the last standby agent message', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
      },
    })

    try {
      await seedCodexTask(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()
      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')

      await expect(agentNode).toBeVisible()
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      const agentBoxBefore = await agentNode.boundingBox()

      const saveButton = agentNode.locator('[data-testid="terminal-node-save-last-message"]')
      await expect(saveButton).toBeVisible()
      await saveButton.click()

      const noteNode = window.locator('.note-node').first()
      await expect(noteNode).toBeVisible()
      await expect(noteNode.locator('[data-testid="note-node-textarea"]')).toHaveValue('All set.')

      const agentBoxAfter = await agentNode.boundingBox()
      const noteBox = await noteNode.boundingBox()
      if (!agentBoxBefore || !agentBoxAfter || !noteBox) {
        throw new Error('Expected agent and note bounding boxes to be available')
      }

      expect(agentBoxAfter.x).toBe(agentBoxBefore.x)
      expect(agentBoxAfter.y).toBe(agentBoxBefore.y)
      expect(noteBox.x).toBe(agentBoxAfter.x + agentBoxAfter.width)
      expect(noteBox.y).toBe(agentBoxAfter.y)
    } finally {
      await electronApp.close()
    }
  })
})
