import { expect, test } from '@playwright/test'
import { execFile } from 'node:child_process'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'
import {
  clearAndSeedWorkspace,
  createTestUserDataDir,
  launchApp,
  readCanvasViewport,
  removePathWithRetry,
  testWorkspacePath,
} from './workspace-canvas.helpers'

const findModifier = process.platform === 'darwin' ? 'Meta' : 'Control'

const execFileAsync = promisify(execFile)

async function createGitWorktree(payload: {
  branchName: string
  worktreePath: string
}): Promise<void> {
  await mkdir(path.dirname(payload.worktreePath), { recursive: true })
  await execFileAsync(
    'git',
    ['worktree', 'add', '-b', payload.branchName, payload.worktreePath, 'HEAD'],
    { cwd: testWorkspacePath },
  )
}

async function removeGitWorktree(payload: {
  branchName: string
  worktreePath: string
}): Promise<void> {
  try {
    await execFileAsync('git', ['worktree', 'remove', '--force', payload.worktreePath], {
      cwd: testWorkspacePath,
    })
  } catch {
    // ignore cleanup failures
  }

  try {
    await execFileAsync('git', ['branch', '-D', payload.branchName], { cwd: testWorkspacePath })
  } catch {
    // ignore cleanup failures
  }

  await removePathWithRetry(payload.worktreePath)
}

test.describe('Workspace Search', () => {
  test('opens via Cmd/Ctrl+F and focuses selected results', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'node-task-search',
            title: 'Fix login bug',
            position: { x: 180, y: 120 },
            width: 520,
            height: 360,
            kind: 'task',
            task: {
              requirement: 'Investigate unicorn-token and patch auth.',
              status: 'todo',
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
          {
            id: 'node-note-search',
            title: 'note',
            position: { x: 860, y: 220 },
            width: 420,
            height: 300,
            kind: 'note',
            task: {
              text: 'Remember banana-token in the incident notes.',
            },
          },
        ],
        {
          settings: {
            focusNodeTargetZoom: 1.37,
          },
        },
      )

      await expect(window.locator('.workspace-canvas')).toBeVisible()
      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeCloseTo(1, 2)

      await window.keyboard.press(`${findModifier}+F`)
      await expect(window.locator('[data-testid="workspace-search"]')).toBeVisible()
      await expect(window.locator('[data-testid="workspace-search-input"]')).toBeFocused()

      await window.keyboard.type('unicorn-token')
      await expect(window.locator('[data-testid="workspace-search"]')).toContainText(
        'Fix login bug',
      )

      await window.keyboard.press('Enter')
      await expect(window.locator('[data-testid="workspace-search"]')).toBeVisible()

      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeCloseTo(1.37, 2)

      await expect(window.locator('[data-testid="workspace-search-input"]')).toBeFocused()

      await window.locator('[data-testid="workspace-search-input"]').fill('banana-token')
      await expect(window.locator('[data-testid="workspace-search"]')).toContainText('Remember')

      await window.locator('[data-testid="workspace-search-item-note:node-note-search"]').click()
      await expect(window.locator('[data-testid="workspace-search"]')).toBeVisible()

      await window.keyboard.press('Escape')
      await expect(window.locator('[data-testid="workspace-search"]')).toBeHidden()
    } finally {
      await electronApp.close()
    }
  })

  test('filters results by category', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'task-search-filter',
            title: 'Filter Task',
            position: { x: 160, y: 120 },
            width: 520,
            height: 360,
            kind: 'task',
            task: {
              requirement: 'Filter token',
              status: 'todo',
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
          {
            id: 'note-search-filter',
            title: 'note',
            position: { x: 840, y: 120 },
            width: 420,
            height: 280,
            kind: 'note',
            task: { text: 'Filter token' },
          },
        ],
        {
          spaces: [
            {
              id: 'space-search-filter',
              name: 'Filter Space',
              directoryPath: testWorkspacePath,
              labelColor: 'green',
              nodeIds: ['note-search-filter'],
              rect: { x: 120, y: 80, width: 620, height: 420 },
            },
          ],
        },
      )

      await window.keyboard.press(`${findModifier}+F`)
      await expect(window.locator('[data-testid="workspace-search"]')).toBeVisible()
      await expect(window.locator('[data-testid="workspace-search-input"]')).toBeFocused()

      const taskItem = window.locator(
        '[data-testid="workspace-search-item-task:task-search-filter"]',
      )
      const noteItem = window.locator(
        '[data-testid="workspace-search-item-note:note-search-filter"]',
      )
      const spaceItem = window.locator(
        '[data-testid="workspace-search-item-space:space-search-filter"]',
      )

      await expect(taskItem).toBeVisible()
      await expect(noteItem).toBeVisible()
      await expect(spaceItem).toBeVisible()

      await window.locator('[data-testid="workspace-search-filter-tasks"]').click()
      await expect(taskItem).toHaveCount(0)
      await expect(noteItem).toBeVisible()
      await expect(spaceItem).toBeVisible()

      await window.locator('[data-testid="workspace-search-filter-notes"]').click()
      await expect(noteItem).toHaveCount(0)
      await expect(spaceItem).toBeVisible()

      await window.locator('[data-testid="workspace-search-filter-all"]').click()
      await expect(taskItem).toBeVisible()
      await expect(noteItem).toBeVisible()
      await expect(spaceItem).toBeVisible()

      await window.locator('[data-testid="workspace-search-filter-spaces"]').click()
      await expect(spaceItem).toHaveCount(0)
      await expect(taskItem).toBeVisible()
      await expect(noteItem).toBeVisible()
    } finally {
      await electronApp.close()
    }
  })

  test('searches spaces/branches and shows space metadata pills', async () => {
    const userDataDir = await createTestUserDataDir()
    const stamp = Date.now()
    const branchName = `e2e/search-meta-${stamp}`
    const worktreeName = `wt-e2e-search-meta-${stamp}`
    const worktreePath = path.join(testWorkspacePath, '.opencove', 'worktrees', worktreeName)

    await createGitWorktree({ branchName, worktreePath })

    try {
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: true,
        env: {
          OPENCOVE_TEST_GITHUB_INTEGRATION: '1',
        },
      })

      try {
        await clearAndSeedWorkspace(
          window,
          [
            {
              id: 'note-search-meta',
              title: 'note',
              position: { x: 240, y: 220 },
              width: 420,
              height: 280,
              kind: 'note',
              task: { text: 'Workspace search metadata pills.' },
            },
            {
              id: 'note-search-root',
              title: 'note',
              position: { x: 920, y: 220 },
              width: 420,
              height: 280,
              kind: 'note',
              task: { text: 'Root space note.' },
            },
          ],
          {
            spaces: [
              {
                id: 'space-search-meta',
                name: 'Meta Space',
                directoryPath: worktreePath,
                labelColor: 'blue',
                nodeIds: ['note-search-meta'],
                rect: { x: 180, y: 160, width: 620, height: 420 },
              },
              {
                id: 'space-search-root',
                name: 'Root Space',
                directoryPath: testWorkspacePath,
                labelColor: 'red',
                nodeIds: ['note-search-root'],
                rect: { x: 860, y: 160, width: 620, height: 420 },
              },
            ],
            activeSpaceId: 'space-search-meta',
          },
        )

        await window.keyboard.press(`${findModifier}+F`)
        await expect(window.locator('[data-testid="workspace-search"]')).toBeVisible()
        await expect(window.locator('[data-testid="workspace-search-input"]')).toBeFocused()

        await window.locator('[data-testid="workspace-search-input"]').fill(branchName)

        const noteItem = window.locator(
          '[data-testid="workspace-search-item-note:note-search-meta"]',
        )
        await expect(noteItem).toBeVisible()
        await expect(noteItem.locator('.workspace-search-panel__pill--space')).toHaveCount(0)

        await expect(
          noteItem.locator('.workspace-search-panel__pill--branch[data-cove-label-color="blue"]'),
        ).toContainText(branchName)
        await expect(
          noteItem.locator('.workspace-search-panel__pill--pr[data-cove-label-color="purple"]'),
        ).toContainText('#123')
        await expect(noteItem.locator('[data-cove-label-color="blue"]').first()).toBeVisible()

        const spaceItem = window.locator(
          '[data-testid="workspace-search-item-space:space-search-meta"]',
        )
        await expect(spaceItem).toBeVisible()
        await expect(
          spaceItem.locator('.workspace-search-panel__pill--branch[data-cove-label-color="blue"]'),
        ).toContainText(branchName)
        await expect(
          spaceItem.locator('.workspace-search-panel__pill--pr[data-cove-label-color="purple"]'),
        ).toContainText('#123')

        await window.locator('[data-testid="workspace-search-input"]').fill('Root Space')

        const rootNoteItem = window.locator(
          '[data-testid="workspace-search-item-note:note-search-root"]',
        )
        await expect(rootNoteItem).toBeVisible()
        await expect(
          rootNoteItem.locator('.workspace-search-panel__pill--space[data-cove-label-color="red"]'),
        ).toContainText('Root Space')
        await expect(rootNoteItem.locator('.workspace-search-panel__pill--branch')).toHaveCount(0)
        await expect(rootNoteItem.locator('.workspace-search-panel__pill--pr')).toHaveCount(0)

        const rootSpaceItem = window.locator(
          '[data-testid="workspace-search-item-space:space-search-root"]',
        )
        await expect(rootSpaceItem).toBeVisible()
        await expect(
          rootSpaceItem.locator(
            '.workspace-search-panel__pill--space[data-cove-label-color="red"]',
          ),
        ).toContainText('Root Space')
        await expect(rootSpaceItem.locator('.workspace-search-panel__pill--branch')).toHaveCount(0)
        await expect(rootSpaceItem.locator('.workspace-search-panel__pill--pr')).toHaveCount(0)
      } finally {
        await electronApp.close()
      }
    } finally {
      await removeGitWorktree({ branchName, worktreePath })
      await removePathWithRetry(userDataDir)
    }
  })

  test('resizes search panel and persists width', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'note-resize-search',
          title: 'note',
          position: { x: 180, y: 120 },
          width: 420,
          height: 260,
          kind: 'note',
          task: { text: 'Resize search panel.' },
        },
      ])

      await window.keyboard.press(`${findModifier}+F`)
      const panel = window.locator('[data-testid="workspace-search"]')
      await expect(panel).toBeVisible()

      const handle = window.locator('[data-testid="workspace-search-resize-handle"]')
      const panelBox = await panel.boundingBox()
      const handleBox = await handle.boundingBox()
      if (!panelBox || !handleBox) {
        throw new Error('Unable to resolve resize handle bounds')
      }

      await window.mouse.move(handleBox.x + handleBox.width / 2, handleBox.y + handleBox.height / 2)
      await window.mouse.down()
      await window.mouse.move(handleBox.x - 120, handleBox.y + handleBox.height / 2)
      await window.mouse.up()

      await expect
        .poll(async () => {
          const nextBox = await panel.boundingBox()
          return nextBox?.width ?? 0
        })
        .toBeGreaterThan(panelBox.width)

      await expect
        .poll(async () => {
          const raw = await window.evaluate(async () => {
            return await window.opencoveApi.persistence.readWorkspaceStateRaw()
          })

          if (!raw) {
            return null
          }

          try {
            const parsed = JSON.parse(raw) as { settings?: { workspaceSearchPanelWidth?: number } }
            return parsed.settings?.workspaceSearchPanelWidth ?? null
          } catch {
            return null
          }
        })
        .toBeGreaterThan(420)
    } finally {
      await electronApp.close()
    }
  })
})
